### ISSUE TITLE
no spool

### ISSUE THREAD

**Issue by Eloura74** [Disane87/spoolman-homeassistant#61]
### System Health details

![image](https://github.com/Disane87/spoolman-homeassistant/assets/95535946/3227e9dd-2fd9-47b0-8f3f-3cd5f326509a)
hello, I can't get the spool and all the information....

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

no spool

### Reproduction steps

1.
2.
3.
...
X

### Debug logs

```text
X
```

**Comment by Disane87** [comment]
You are in the system health system of HA. You have to navigate to the integrations and than spoolman to see any spools

**Comment by Disane87** [comment]
Could you activate the debug logs and look into the HA logs? I guess this could be problem with your spools Actually there is a bug #58 which occurs when you don't have a vendor set iun the spool in spoolman

**Comment by Eloura74** [comment]
![image](https://github.com/Disane87/spoolman-homeassistant/assets/95535946/6c2259ad-0a7c-42e6-82f1-2d623090518e)
great that came from that, thank you very much

**Comment by Eloura74** [comment]
Do you have an example of a nice map proposed for the dashboard?

**Comment by Disane87** [comment]
You can use the default `entities` card for this:
![image](https://github.com/Disane87/spoolman-homeassistant/assets/956158/fac27df2-c7e8-46db-8cbb-40dea24fbc33)

Or `auto-entities-card` for getting all entities by this integration dynamically:
https://github.com/thomasloven/lovelace-auto-entities

And some `mushroom-entity` cards for example.
https://github.com/piitaya/lovelace-mushroom/blob/main/docs/cards/entity.md

**Comment by Disane87** [comment]
I've created a simple card utilizing `mushroom-template-card` and `auto-entities` to dynamically show all spools:
```yaml
type: custom:auto-entities
filter:
  include:
    - integration: '*spoolman*'
      options:
        type: custom:mushroom-template-card
        vertical: false
        icon_color: >- 
          #{{ state_attr(entity, 'filament_color_hex') }}
        icon: 'mdi:printer-3d'
        primary: >- 
          {{ state_attr(entity, 'filament_name') }}
        secondary:  >- 
          {{ (state_attr(entity, 'remaining_weight')/ 1000 | float)  | round(1) }} kg
        
sort:
  method: state
  reverse: true
card:
  type: grid
  columns: 2
  square: false
card_param: cards

```

![image](https://github.com/Disane87/spoolman-homeassistant/assets/956158/08d4e89d-211a-42bd-92dc-52226c171d52)

It's pretty neat. I think I gonna document this in the readme.
